backend = "glx"
glx-no-stencil = true
vsync = true
swi-opti = "xrender-sync"

shadow = true
shadow-radius = 20
shadow-opacity = 0.6
shadow-offset-x = -10
shadow-offset-y = -10

shadow-exclude = [
  "class_g = 'Polybar'"
];

fading = true
fade-in-step = 0.05;
fade-out-step = 0.05;

corner-radius = 10

rounded-corners-exclude = [
  #"window_type = 'normal'",
  "class_g = 'Polybar'",
  "class_g = 'Onboard'"
];
